### ISSUE TITLE
Fix for JetBooking or purchase plugins etc - Protect purchase end value

### ISSUE THREAD

**Issue by edgBlw** [CrocoBlock/suggestions#5280] opened 2022-04-28 08:53 UTC
do i even have to say something?

https://user-images.githubusercontent.com/101653721/165715454-0794816c-2ec4-4383-92ac-b09cde0f8989.mp4

**Comment by girafffee** [comment] 2022-04-28 15:06
Hi, the problem is already fixed in Foreo dynamic template and JetFormBuilder. You can check the fix on the same page

**Closed as completed** 2022-05-09 12:43 UTC
