### ISSUE TITLE
Improve AJAX Performance (JetEngine / JetSmartFilters) / Unusable with Elementor 3.6

### ISSUE THREAD

**Issue by valmirselmani** [CrocoBlock/suggestions#5639] opened 2022-07-13 11:34 UTC
Loading posts via AJAX wasn't exactly fast to begin with, but with the Elementor 3.6 update, it's now even worse.
I would say it is unusable.

Test results with CPT, which has about 250 posts. But it is also very slow when it has only 10 to 20 posts.

**Elementor 3.5**
**Listing Grid (load 27 posts):** 1.5 to 2 seconds
**Listing Grid (JetSmartFilter):** 1.5 to 3 seconds
**Listing Grid (Reset Filter):** 1.5 to 2 seconds

![jetengine_elementor_3_5](https://user-images.githubusercontent.com/1654866/178724332-5e8d1367-70af-49b3-b973-ae4fda226224.jpg)

**Elementor 3.6** 
**Listing Grid (load 27 posts):** 5.5 to 8 seconds
**Listing Grid (JetSmartFilter):** 6 to 16 seconds
**Listing Grid (Reset Filter):** 6 to 16 seconds

![jetengine_elementor_3_6](https://user-images.githubusercontent.com/1654866/178724324-c6e789e4-a455-4dfc-a689-e74477c33f43.jpg)

Tested on the same website, the same server, the same plugins. Only with the update to Elementor 3.6.
I've been holding off updating to Elementor 3.6 because of the terrible performance.

Please investigate this issue as we have several large customers that rely on this feature.

I think it has something to do with Elementor. Maybe it's a good idea to talk to the Elementor development team and clarify the issues. Maybe they changed something with the rendering, which is much slower now.

However, JetEngine and JetSmartFilters could also be improved, there is still a lot of room for improvement, especially performance. The plugins are awesome aside from the terrible performance for filtering.

**Comment by trofimartya** [comment] 2022-07-13 14:29
+1

**Comment by mehdimoradi1500** [comment] 2022-07-13 19:19
+1

**Comment by 79ho3ein** [comment] 2022-07-13 19:28
+1

**Comment by unitedonline** [comment] 2022-07-14 14:24
+1

**Comment by MjHead** [comment] 2022-07-15 17:53
@valmirselmani Maybe you have a staging website with the problem where we can test it, or at least reproduce the listing? Because I tested this on 500+ posts and 12 posts per page - all results less than 1 second - https://i.imgur.com/o2YVO7R.png So looks like this is not common problem, maybe the issue with some specific widgets used in listing

**Comment by valmirselmani** [comment] 2022-07-15 19:06
@MjHead I could reproduce your results with a listing grid displaying only one image, a listing with multiple dynamic fields, in my case 8 custom fields. Did you test locally or on a server?

I would need some time to create a staging site where you can investigate the problem. In the meantime you can test with with multiple custom fields and see if that's the problem. However, I believe the problem is related to Elementor 3.6. They must have changed something. The same site with Elementor 3.5 is considerably faster.

It would be great if you can focus on performance in your next release. Maybe you can take some ideas from Gridbuilder (https://wpgridbuilder.com/), like Indexed Table, Custom Ajax Endpoint. If you can provide the same level of performance as the other plugin, that would be awesome.

**Comment by mehdimoradi1500** [comment] 2022-07-15 22:55
I completely agree with @valmirselmani
I have heard so much in Facebook groups and all complaining about the performance of crocoblock plugins especially JetEngine
I have tried wp grid builder its so fast and has better performance

**Comment by MjHead** [comment] 2022-07-19 10:56
At the moment there is no issue with quering data, its rendering part. In this case speed totally depends on number of elements inside of listing grid item. Here is an example with Elementor 3.6.7 + Listing Grid + Filters - as you see, the most difference on the filter response time is related the number of Elements should be build. Unfortunately we haven't a lot of possibilities to impact on default widgets where Dynamic Tags used, only on dynamic wdgets from JetEngine and at the moment we testing on solution to speed up the render process. Hope in a few days we'll can release a beta and you'll can test.

**Comment by valmirselmani** [comment] 2022-07-19 11:07
@MjHead Thanks for following up. It's always nice to see a company listen to feedback, and you guys have proven that time and time again with the new features for the plugins. You guys have laid a great foundation with the plugins, just a few improvements in performance and some other features would make your plugins even more awesome.

I thought it was the rendering, since I only changed the Elementor version. Maybe it's because Elementor is working on the underlying structure so that nested elements are possible later. Maybe you can ask the Elementor Dev Team what exactly has changed so you can better address the issue.

**Comment by mehdimoradi1500** [comment] 2022-07-19 11:13
Yes its so good to listen to the community, i think if crocoblock focus on the plugins without any reliance on page builders it will better
And yes we like to see jetEngine to be so fast and with great performance.

Im using bricksbuilder with JetEngine and it has cool features to render datas! You can use several dynamic tags in one text element!

**Comment by valmirselmani** [comment] 2022-07-19 16:39
@mehdimoradi1500 That's actually a very good idea, to be able to use multiple dynamic tags in the same text element. That would improve the performance a bit in my case.

@MjHead Is it possible to develop a feature where we can insert e.g. multiple dynamic tags or multiple meta fields in a text element? I am aware that it is possible to do this using the Shortcode Generator, but this solution is not so elegant. 

It is tedious e.g. when I want to show first name and last name or a whole address (street, zip, city,...) in one listing. In the current implementation I would have to use two Dynamic Fields and make them inline so they are displayed next to each other.

**Comment by MjHead** [comment] 2022-07-20 08:33
omg, forgot to add a link into my previous comment - https://crorotest.kinsta.cloud/woocommerce-listing/

**Comment by MjHead** [comment] 2022-07-20 08:46
As for Elementor update - I think I found where is the problem, we'll investigate it deeply, but looks like it caused the more solid logic of set up widget settings when a new widget instance initiated before rendering.

@valmirselmani As for combinig of meta fields - at the moment the shortcode from shortcode generator is only option for this. We are planning a significantly improve it with 3.1 update, make it similar to dynamic field widget by functionality. From performance side it will allow you to improve a speed in the way you said - by combinig couple of fields in a single widget. Because now something around 90% of rendering single Dynamic Field widget time is initiating Elementor widget, and only 10% it a rendering widget content itself. Also if you have no too complicated layout of Listing Item, you can build it with Blocks editor and style manually with CSS

**Comment by 79ho3ein** [comment] 2022-07-20 09:27
hi @MjHead , According to the elementor developers, they are heavily rewriting and developing their infrastructure these days to add great features that users are asking for. So it seems that the Ajax speed drop in elementor is for this reason.
Especially the version 3.7 elementor beta, which has not yet been officially released, has been a large part of the changes in the infrastructure. Therefore, after the release of version 3.7, Ajax slowdowns and other things may be exacerbated.
In the recent elementor updates, the Ajax speed of the JetSearch plugin has been greatly reduced. Maybe close to 4 seconds. While it was not the case before. Also for jet smart filters plugin.

**Comment by valmirselmani** [comment] 2022-08-15 11:21
@MjHead Sorry for the late reply, I was away for three weeks. This sounds great! When can we expect the 3.1 beta?

**Comment by valmirselmani** [comment] 2022-08-31 11:00
@MjHead Any updates on the 3.1 release? I am still holding off on updating from Elementor 3.5 to 3.7 because of the performance issues when using multiple dynamic field widgets.

**Comment by MjHead** [comment] 2022-09-06 18:54
@valmirselmani Sorry for the delay. Partially these was fixed with JetEngine 3.0.3. For me it was somwthing around 50% faster listing grid rendering. At the moment not sure if it could be improved without breaking compatibility with some parts of Elementor. So more improvements with this will arrive later, not with 3.1.0, but after it

**Comment by valmirselmani** [comment] 2022-09-07 11:09
@MjHead  No problem. You mentioned the feature where you can combine multiple Dynamic Field Widgets into one by displaying multiple meta fields with the same widget.
That's exactly the problem, that every dynamic field widget needs an initialization time.
But if instead of for example 8 widgets you only need 1 widget to display the same data. Then the problem is solved for now.

Will this feature come with 3.1.0 or later? When can we expect the 3.1.0 update?

**Comment by Michaelgimii** [comment] 2022-09-07 12:52
hi @MjHead , Will we see this 50% improvement in the new version of jet smart filters or is it only applied to the jet engine? Are there any plans for a new version of jet smart filters? Thanks in advance

**Comment by mehdimoradi1500** [comment] 2022-09-07 12:59
Also i saw a post on Facebook group, talked about a fully new version of jet smart filter. Is there any news about it?

**Comment by valmirselmani** [comment] 2022-09-12 19:35
@MjHead A bit more information to solve this problem. I have observed that the same page that takes 5 seconds to load the posts via Ajax (reset filter for example), takes only one second to load without Ajax (when you visit the page without filters). 

On a side note, if you use maps, the pins are updated almost instantly and the listing grid takes 3-4 seconds longer below the map.

So it can't be just Elementor. It also has something to do with the Ajax handler, I think.
Can't you implement some sort of cache to speed up the process? Maybe use transients and create for each post and listing type a transient that it doesn't have to be initialized again and again for each request?

I'm really frustrated that every new page I set up and filter a few posts (5 or 10 posts) takes forever to load.
I have 3 sites (which all use JetEngine and JetSmartFilter) scheduled to go live this month and all are unacceptable in terms of filtering speed. Please prioritize this issue over anything else.

**Comment by karifritsch** [comment] 2022-09-26 17:12
Similarly to @valmirselmani I have filters for a map listing and a listing grid with the same information. The map listing is far faster than the listing grid in every way, from initial page load to ajax filtering.

Listings always take seconds to load, even if the listing template has a total of two dynamic widgets getting text. This happens across client websites. I can get a product loop from JetWoobuilder to load instantly (but doesn't display dynamic widgets for me) where the listing grid will take 5+ seconds, even if I'm asking it to load only 9 listings on the page to start.

Because the listing grid is so utterly slow, I definitely get frustrated that other Jet plugins (JetWoobuilder, etc.) do not give the same abilities, like getting glossary labels. It's like I'm being forced to use JetEngine widgets when Crocoblock already has dedicated plugins. The shortcode to combine dynamic fields will be really welcome.

I have heading/dynamic field combos, use custom width in 50% to get it all to line up, have to set up dynamic visibility for the heading to get the illusion of two columns of meta data products don't always have the same info:
HP          10
Amp       50
Volts      --   (hidden)

**Comment by gentleShark** [comment] 2022-10-19 17:50
@valmirselmani Sadly, it seems Crocoblock does not even test for performance and their solution is to tell the customer it's fast enough. My chat with them today:

Vadim: Our templates do not slow down the site. Performance depends on the server and on caching

Me: I've installed the crocoblock dynamic websites in multiple environments, on hosted wordpress and on a VPS with plenty of CPU and RAM. The dynamic websites were unusably slow on hosted sites and were very slow on a powerful VPS. Even on your demo server which is likely optimized it takes 5 seconds or so for an AJAX filter request to update the results (https://demo.crocoblock.com/balirento-new/listing-grid/) and this is not filtering a lot of data. I wonder if the request would ever complete if there were 1000 records. Is there any performance/load testing you can share with me?

Vadim: **Unfortunately, we do not have performance tests**

Me: unfortunately, that explains why it is slow.

**Comment by mateitudor** [comment] 2022-10-20 07:23
Unfortunately this is the case with many plugin developers: "works fine for me ¯\_(ツ)_/¯" & then close tickets or just ignore them. Disappointed it's the case with Crocoblock.

**Comment by Mrgreen93** [comment] 2022-10-20 07:42
I believe they should focus on the performance of their plugins and improve the existing features, Not just adding features.

**Comment by mindstep** [comment] 2022-11-08 13:50
> I have tried wp grid builder its so fast and has better performance

Awesome, exactly what I was looking for, thanks!

**Comment by Cosirax** [comment] 2022-11-26 01:35
Hey there, I really enjoy the crocblock "Univers" they have a  wide  functionallity but indeed.. the performance, especially for the listing grid is so poor. I have a production site setup which has now about 80 entries (not that much, normally...) who have 8 acf fields. This page is loading 16s (!) on a high performance server. Thats not usable. If there won't be an update in the close future I will be forced to change listing plugin und several pages.

Hey, Crocoblock, please, don't ignore this and put it on your top of the todo list. Do performance improvements so that  we can use your plugins further.

Hopefully lookin' forward seeing some nice updates! Thanks for all the work, keep it up!

**Comment by justdave007** [comment] 2022-11-28 05:00
+1 on this request.  We used this for a client site, and it is soooo slow it's basically unusable. >10s for a filter to apply and refresh.  We'll have to recreate this feature, wasting a bunch of time, and this was the only reason we paid for crocoblock.

**Comment by mrkoq** [comment] 2022-12-02 11:59
Same problem here - huge loading times when applying filters, from a user perspective its unusable.

Anyone got a solution or is Crocoblock working on it?

**Comment by Cosirax** [comment] 2022-12-02 12:33
> Same problem here - huge loading times when applying filters, from a user perspective its unusable.
> 
> Anyone got a solution or is Crocoblock working on it?

It doesn't feel like they are working on it since this thread began in july. If you need working, fast filters give wp gridbuilder a try. I've switched to this plugin because it's quite fast even on listings  with more than 200 posts

**Comment by Mrgreen93** [comment] 2022-12-02 12:36
Hi @Cosirax, i think mjhead said that they are working on it
But is wp grid builder adaptable with JetEngine? Thank you

**Comment by gentleShark** [comment] 2022-12-02 17:40
> Hi @Cosirax, i think mjhead said that they are working on it But is wp grid builder adaptable with JetEngine? Thank you

I contacted WP Grid Builder and they said their filters work with Jet Engine custom post types. Haven't tried it yet though. Let us know how it goes.

**Comment by Mrgreen93** [comment] 2022-12-03 22:24
Thanks hope they support it as well
By the way crocoblock should focus on the performance of their main plugins like JetEngine and JSF
We trusted them so if their plugin be bloated or slow, we don't feel good experience

**Comment by dburke-ux** [comment] 2022-12-16 14:41
I reached out the WPGridBuilder support to ask about compatibility with JetEngine. Their response:

> WP Grid Builder is compatible with any (custom) post type. In order to make it work the custom post type must be publicly queriable and searchable. However, there isn't any integration for custom fields created with Jet Engine. It means that if you use a custom field that store an array/object it will not work. It will only work with simple field that stores text/number.

So, while basic support is there, the lack of support for arrays probably means you won't be able to do anything too fancy

**Comment by Mrgreen93** [comment] 2023-01-10 22:07
Hi @MjHead 
When i load my sites with and without JetEngine, its a quite big difference in the sources. Actually JetEngine loads a lot on the background.
Is there any plan to improve the performance?

**Comment by yasinishyn** [comment] 2023-01-11 15:57
Same problem. The UI is fast, but the Ajax request takes 2-3 seconds.
There is no way to cache the response on the backend side?

**Comment by Joliamendi** [comment] 2023-01-11 17:50
Elementor is now in version 3.10. Is there still no news of a fix for this problem?

**Comment by paraimpacto** [comment] 2023-01-11 23:10
Hi we are also experiencing very slow load times. Would be great to have some sort of solution either via caching or some sort of preloading warmup. In fact, the page header and menu don't even load first...essentially only a white page for 3 t0 15 seconds. Jet Smart is awesome, but this kind of sucks:(

**Comment by hb81010** [comment] 2023-01-24 08:22
Has anyone had any experience in Bricks with SmartFilers? Maybe it runs better there

**Comment by PieterBrink** [comment] 2023-02-10 06:16
> Has anyone had any experience in Bricks with SmartFilers? Maybe it runs better there

good question - doubt it - will test and revert! I am new to bricks but damn it is amazing!  Sooo fast. More Bricks builder and Crocobloc - can you imagine the possibilities!

**Comment by Zegklitz** [comment] 2023-02-14 15:26
+1

**Comment by rentaterry** [comment] 2023-02-18 12:18
> > Has anyone had any experience in Bricks with SmartFilers? Maybe it runs better there
> 
> good question - doubt it - will test and revert! I am new to bricks but damn it is amazing! Sooo fast. More Bricks builder and Crocobloc - can you imagine the possibilities!

I have switched to Bricks builder after some simple testing about Listing Grid, JetSmartFilters. I couldn't believe my eyes that, by loading 100 posts per page. Same server same settings. See the result down below:
![2](https://user-images.githubusercontent.com/75129305/219865226-3ac932e2-afdb-4ea7-94de-7fd2965d711e.png)
![1](https://user-images.githubusercontent.com/75129305/219865229-98128a94-7807-4901-a513-f241ef89d4c6.png)

Now I am rebuilding my pretty complex site and over 40 plugins activated with Bricks and still crazily fast WITHOUT caching. Everyone who are concerning about speed and performance, stop bagging those things from Elementor. They are no hope.

**Comment by PieterBrink** [comment] 2023-02-18 15:44
Amasing @rentaterry! thanks for the update!

**Comment by gentleShark** [comment] 2023-02-18 15:55
Bricks Builder looks promising but to be fair, Crocoblock is not from
Elementor and Elementor is not plagued with performance issues like
Crocoblock. It's easy to get Elementor sites to be 100/100 on Google
pagespeed tests.

**Comment by hb81010** [comment] 2023-02-18 15:58
I had now also only in a high-performance dev environment some listings in use, which had, however, a maximum of only 10 products, but in each case a lot of meta data and from the feeling, it was also significantly faster for me. Not much difference to the WP GridBuilder and felt by the suport of the Bricks Query Loop I could again determine an improvement.

But a 1:1 comparison I could not make yet, because my dev environment compared to my other hosting is much stronger with 16 GB RAM, 4 vCores, Nvme and 1024 MB PHP memory limit.

**Comment by rentaterry** [comment] 2023-02-18 16:00
> 

Try Bricks before you saying "Elementor is not plagued with performance issues like
Crocoblock". I am not making advertising for Bricks since they have refund policy. I am a real customer, paying LTD for the plugin and capturing the speed fact and you know what, you disagreed by simply typing few words. I won't say anything for the ones who did not do any comparison and judge me with no sense.

**Comment by rentaterry** [comment] 2023-02-18 16:02
> I had now also only in a high-performance dev environment some listings in use, which had, however, a maximum of only 10 products, but in each case a lot of meta data and from the feeling, it was also significantly faster for me. Not much difference to the WP GridBuilder and felt by the suport of the Bricks Query Loop I could again determine an improvement.
> 
> But a 1:1 comparison I could not make yet, because my dev environment compared to my other hosting is much stronger with 16 GB RAM, 4 vCores, Nvme and 1024 MB PHP memory limit.

That was wired. I tried 100 posts per page and loading with about 2 seconds in 2 core 4gb ram server. I used to test the Elementor environment with 16core 64bg ram. Sadly it was the same

**Comment by hb81010** [comment] 2023-02-18 16:18
> > I had now also only in a high-performance dev environment some listings in use, which had, however, a maximum of only 10 products, but in each case a lot of meta data and from the feeling, it was also significantly faster for me. Not much difference to the WP GridBuilder and felt by the suport of the Bricks Query Loop I could again determine an improvement.
> > But a 1:1 comparison I could not make yet, because my dev environment compared to my other hosting is much stronger with 16 GB RAM, 4 vCores, Nvme and 1024 MB PHP memory limit.
> 
> That was wired. I tried 100 posts per page and loading with about 2 seconds in 2 core 4gb ram server. I used to test the Elementor environment with 16core 64bg ram. Sadly it was the same


This sounds very good and I think Crocoblock is on the right track. Here is an example from me. Almost 20 filters with 10 products. Every change is done instantly. 

https://www.loom.com/share/224020af5f024b74befc1b3b755c0d69

**Comment by lorikthinks** [comment] 2023-03-07 08:15
So what's the fix for this now? I have a website in production that has over 200 posts available, but it takes on average **2 whole seconds** before the server responds. Is there at least a _temporary_ fix for now?

**Comment by cgraider** [comment] 2023-03-27 10:32
My client is not satisfied with this also, Crocoblock any suggestions?

**Comment by lorikthinks** [comment] 2023-03-27 11:32
> My client is not satisfied with this also, Crocoblock any suggestions?

Personally I switched to [Gridbuilder](https://wpgridbuilder.com), but it took a bit of time to set up (the cards are not very customisable). It is very fast though, so that's nice. And the filter building is also very easy.

**Comment by meisterleise** [comment] 2023-05-10 20:59
I have got this problem too. Any filter: 4 sec., filter reset 7 sec. !!
@Crocoblock this thread is very old. Is there any chance that this will improve at some point?
Otherwise we have to switch to gruidbuilder too. :((

**Comment by JanWebofka** [comment] 2023-05-12 06:40
So as i was looking for a way to speed up Ajax for jetengine listing grid, i came across this thread and dont see any option only to switch to Gridbuilder ?

**Comment by klaatu-code** [comment] 2023-05-13 11:14
I don't understand why don't they add at least an announcement without any date or something. It appears very disheartening given the timeline. 

It seems that they went silent and at this point, it is worrying for me. Like I need to decide if should I start a new project which will have up to 1000 listings and use JetEngine or switch to alternatives. 

Can anyone from the official channels post an update about the issue?

**Comment by fatjay1979** [comment] 2023-05-21 09:47
Sorry .. but i must also say... its shocking that they are no improvments about this.  I just checked Gruidbilder .. and it feels in their demo 100 times faster and smoother then jet filters.  Come on guys... pls fix this.

**Comment by paraimpacto** [comment] 2023-05-21 14:40
As a point of reference, we did switch to Gridbuilder. We still use Jetsmart for different filtering functionality on another site, and we really love it. The Gridbuilder has proven to be  more scalable. Here is one filter we built that could not be realized at the same loading speed as Jetsmart. https://baseworks.com/instructors/

**Comment by Arian-c27** [comment] 2023-06-09 03:26
With 250 posts query time is insignificant. Issue is indeed elementor. All the time is spent rendering the widgets and templates for each result. The end result is delays and wasted server resources. 

I recommend trying this free plugin. It’s a custom version of elementor tackling this specific issue

https://getvoxel.io/docs/voxel-elements-beta/

PS: I’m a theme dev and some customer linked me this thread as we also utilize elementor in our themes. Feel free to delete if inappropriate

**Comment by neylwalecki** [comment] 2023-08-17 03:13
+1 more speed on the smartsearch filters pleaseee

**Comment by lbehet** [comment] 2023-08-22 09:30
We have the same problem. This is an essential function for us, if there are no optimizations, we too have to look for another alternative.

**Comment by MjHead** [comment] 2023-11-14 12:22
With 3.3.0 added Timber/Twig views, which are much faster than Elementor-based listing items on regular render and on filtering. Here is avg benchmarks for the simple listing item with the same amount of content for each builder:
<img width="1284" alt="image" src="https://github.com/Crocoblock/suggestions/assets/4987981/c340b340-9343-43e3-afee-260e6fd50800">
 As for speeding up Elementor listing items - at the moment we faced a bottleneck - we can't make it faster than Timber/Twig or Blocks listings, because Elementor itself do much more work on it's own side - to create instance of each widget, validate it and than render

**Closed as completed by MjHead** 2023-11-14 12:22 UTC

**Comment by JJAsh1** [comment] 2024-01-03 13:52
+1 more speed on Jet smart filters. It's so slow !

**Comment by klaatu-code** [comment] 2024-01-03 14:35
We moved to https://getvoxel.io/ and couldn't be happier. It flies x1000 and all the same stuff in a different way.
