### ISSUE TITLE
Ajax Search widget settings throws error on PHP8.

### ISSUE THREAD

**Issue by cvl01** [CrocoBlock/suggestions#6638] opened 2023-03-20 12:44 UTC
**Describe the bug**
`TypeError: strpos(): Argument #1 ($haystack) must be of type string, array given`
In `jet-engine/jet-engine.php` on `line 233`, function `init_knowledge_base_search()`

**To Reproduce**
Using the **Ajax Search** widget, when searching for **Terms** in the **Search Query** settings panel, the error above is thrown and terms are not returned. This makes the Ajax Search widget unusable. 

Issue only occurs using PHP version >8.

**Expected behavior**
Return terms for search term.

**Comment by cvl01** [comment] 2023-04-13 10:52
Any update? Error is still present in the latest release

**Comment by kaskad88** [comment] 2023-04-19 10:32
Hello @cvl01. 
Could you please attach a screen or describe more detail because I tried to reproduce your issue and looks like all works fine.
Or contact our support https://crocoblock.com/help-center/ for guidance in resolving this issue (and mention that you were directed by me and reference this issue.)

**Closed as completed** 2023-04-26 11:11 UTC
