### ISSUE TITLE
BUG : jet smart filters counter align - 3.0.2 version

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#6217] opened 2022-11-29 18:03 UTC
**Describe the bug**

Hi @Floydtm and @SargasTM , First of all, thank you for fixing the problem of filters in RTL.
In the new version, there is a bug related to counters. **This bug occurs in both RTL and RTL.**

In this version, if counters are enabled, the counters are not centered and are actually slightly higher than they should be. Please look at the image below : 

![counters](https://user-images.githubusercontent.com/77163248/204606776-ed70c13e-3c8d-4af7-9144-663e41709bd2.png)

By adding a 5px margin from the top, everything goes well.

![s](https://user-images.githubusercontent.com/77163248/204608720-c0e5bd7f-c081-4898-9a79-798f0b3f30da.png)

Please check this bug if possible. **It should be noted that this bug also exists in checkbox and radio filters, but less.**

thank you!

**Comment by morosmo** [comment] 2022-11-30 06:01
+1
Same for LTR (English versions)

**Comment by SargasTM** [comment] 2022-11-30 07:59
thanks, i'll fix it

**Comment by Michaelgimii** [comment] 2022-11-30 08:50
+1
same here

Hi @SargasTM , Please keep in mind the possibility of moving the counters to the opposite side as well as removing the parentheses from the counters. Below is the image on your official website that covers these two features. I don't know how hard it is for you to implement these two features, but please keep these two features in mind.

![download](https://user-images.githubusercontent.com/88034902/204751295-d9456158-f57f-4623-88dc-c37c374237d1.png)

thanks!

**Comment by SargasTM** [comment] 2022-11-30 09:09
@79ho3ein  I don't have margin-top, and I didn't find that it was added in the code. Try to recreate this filter, maybe the old css

**Comment by 79ho3ein** [comment] 2022-11-30 09:32
@SargasTM , I have added margin-top code in chrome inspect.

**Comment by Michaelgimii** [comment] 2022-12-02 12:46
Hi @SargasTM 
Were you successful in reproducing this bug? Will it be fixed in the next version?

**Comment by SargasTM** [comment] 2022-12-02 16:10
no bug here
counter is centered
<img width="175" alt="image" src="https://user-images.githubusercontent.com/5094971/205334336-2b7ec5c0-0aca-40ee-bebc-6bf0bd5d0577.png">

maybe in the next version just replace the control "Horizontal Offset" from the slider
<img width="280" alt="image" src="https://user-images.githubusercontent.com/5094971/205335522-2a3c70d8-4966-4f3b-ac37-f96e903a000a.png">
 to Margin
<img width="274" alt="image" src="https://user-images.githubusercontent.com/5094971/205335815-95f08b3b-2138-4b4d-9359-d94951b37290.png">

**Comment by 79ho3ein** [comment] 2022-12-02 16:20
Hi @SargasTM 
Adding margin control to the counter would be great. But it is strange that by default the counter is not a problem for you. I will look into this further.

Thank you

**Comment by 79ho3ein** [comment] 2022-12-02 16:30
@SargasTM , I forgot to say one thing. In the screenshot you posted, you checked this bug in the checkbox filter. But if you check it in the **visual filter**, there is definitely a problem with the alignment of the counters in this widget.

![download](https://user-images.githubusercontent.com/77163248/205339915-4fc3c31b-ccc1-4e29-ac0e-875dce05297f.png)

**Comment by Michaelgimii** [comment] 2022-12-02 16:53
@SargasTM 
**The counter alignment bug exists only in the visual filter.**

![jet smart](https://user-images.githubusercontent.com/88034902/205342986-f714d906-a7ba-4f4b-a6a0-99b6b5ede19e.png)

But if you add a checkbox filter, the counters are in exactly the right place. In the picture below, the difference is quite clear.

![visual filter](https://user-images.githubusercontent.com/88034902/205343891-36350843-f173-4b08-be17-72ec479ac547.png)

**Comment by SargasTM** [comment] 2022-12-02 16:58
yes, the problem is in the visual filter
thanks, I'll fix it

**Comment by Michaelgimii** [comment] 2022-12-06 14:38
Hi again @SargasTM , Please check this. It is an important bug in its own right. https://github.com/Crocoblock/suggestions/issues/3366
thanks

**Comment by SargasTM** [comment] 2022-12-09 11:00
indexer counter fixed, will appear in the next release

**Closed as completed by SargasTM** 2022-12-09 11:00 UTC
