### ISSUE TITLE
Allow admin to use Jet plugins on staging site

### ISSUE THREAD

**Issue by developernerds** [CrocoBlock/suggestions#2663] opened 2021-02-17 22:56 UTC
I would love it if you would allow admins to use the plugins on their staging sites. You can do it like Elementor does by allowing use only on sites like the following...

TLD (Top-level Domain) that are not considered as a license: 

*.dev (example.dev)

*.local (example.local)

*.staging (example.staging)

*.test (example.test)

*.example (example.example)

*.invalid (example.invalid)

Subdomains that are not considered as a license:

dev.* (dev.example.com)

local.* (local.example.com)

test.* (test.example.com)

staging.* (staging.example.com)

This will allow us to keep our staging site up to date because we have already paid to use it on our site, so if we are only using it to develop our site from a staging site, I think it should be allowed without having to pay again for using the plugin essentially on the same site. :)

**Comment by Rubenzella** [comment] 2021-08-23 00:38
Duplicate of https://github.com/Crocoblock/suggestions/issues/3182

**Closed as completed** 2021-09-10 09:59 UTC
