### ISSUE TITLE
Bug - Bricks (JetEngine) - Some Field (Image, Price) not working in Bricks JE Posts Query since 3.3.2

### ISSUE THREAD

**Issue by hb81010** [CrocoBlock/suggestions#7273] opened 2023-12-31 12:48 UTC
WP: 6.4.2
Bricks: 1.9.4
JetEngine: 3.3.2.1

I have created a meta field of the field type "Posts" for my posts. I use it to link to other posts.
This also worked perfectly. Since update 3.3.2 the thumbnail {featured_image} no longer works and only the thumbnail of the current post is displayed. Other fields work fine.

**1.) Meta-Field**
![1-MetaField](https://github.com/Crocoblock/suggestions/assets/54399588/47fafb62-d498-472f-9367-c0261d40f9e7)

**2.) Linked Post**
![2-Linked-Posts](https://github.com/Crocoblock/suggestions/assets/54399588/77e80f29-73b3-4d2d-8152-e7a2f350984b)

**3.) Query**
![3-Query](https://github.com/Crocoblock/suggestions/assets/54399588/c44aebbe-29d3-46fd-ab94-610e6a09198d)

**4.) My Structure Panel**
![4-Structure Panel](https://github.com/Crocoblock/suggestions/assets/54399588/903c59b1-de8d-405e-925e-72cc6c784f20)

I have also set it on a new local instance where only JetEngine is activated as a plugin.

When I roll back to version 3.3.1 it works again and the correct thumbnail is displayed again

![5-Rollback](https://github.com/Crocoblock/suggestions/assets/54399588/e3bc5826-520d-4183-b319-2e7bca73f3d0)

**Comment by hb81010** [comment] 2023-12-31 13:32
Addition:
For example, the price does not work for products too. Only the price of the current product page is displayed

![grafik](https://github.com/Crocoblock/suggestions/assets/54399588/2b8b8ad4-ebb3-4dc4-a065-82160450ba9a)

Links (buttons), names all work without problems

**Comment by cwinkler8** [comment] 2024-01-11 16:32
I'm facing similar issues and have rolled back to 3.3.1. I initially submitted a bug report to the Bricks team, but their investigation directed me back to the Crocoblock team. Here is the link to my report and their investigation... 
https://forum.bricksbuilder.io/t/no-bug-query-loop-not-displaying-dynamic-fields-from-jetengine-cpt/18521

**Comment by hb81010** [comment] 2024-01-28 16:16
Is there an update for this? Unfortunately its been over a month and there was no fix in the last JetEngine update

**Comment by cwinkler8** [comment] 2024-02-01 14:13
Unfortunately the latest update did not solve the issue, I had to roll back to 3.3.1 again.

**Comment by cwinkler8** [comment] 2024-02-08 17:00
@MjHead or @RagnarLodbrok94 , can you please confirm that this is the same issue?

There is still a bug when rendering related posts in a Bricks query loop...the featured image and meta fields are not displayed. The issue first appeared in 3.3.2, so I have rolled back to 3.3.1 and it works correctly.
I was hopeful that this note in the changelog for JE 3.3.5 would address the issue, but it did not.  "FIX: Display Dynamic Field content in the Bricks template;"

**Comment by hb81010** [comment] 2024-02-10 09:19
I think the communication is a real shame and I am really thinking about switching to MetaBox. There are now 5 versions in between that I cant update...

It really feels like the updates for Bricks are not tested as extensively before release as for Elementor

I am aware of 2-3 more bugs. However, I really dont want to waste my time every time and report them if the response is extremely slow or non-existent.

**Comment by MjHead** [comment] 2024-02-15 05:48
@hb81010 @cwinkler8 Thanks for the reporting and sorry for the delay. We just take it into the work. As for situation itself - this is public Git used for both - feature requests and bug reports. As you can se there are 3.6k opened issues here. If you have any critical bugs need to be fixed asap - there is Crocoblock support for such reason - https://crocoblock.com/help-center/. Each release could take only 10-15 issues on the board. And issues from internal support requests has higher priority, than from a public git. It's not because they are more important, just because they're more controlled - easier communication with client, more people involved, easier to investigate issue at client side.

**Comment by cwinkler8** [comment] 2024-02-15 14:19
@MjHead thanks for the follow-up and I can certainly appreciate the volume of requests given the breadth of the Crocoblock suite. I actually did create a support ticket (#171036) first and then indicated that I had found this issue in Git. Should I have asked them to escalate the ticket, create a new one, or is there something else I should have done? Thanks!

**Comment by hb81010** [comment] 2024-02-15 15:20
@MjHead 
Thanks for the answer and the explanation.

I am also happy to go through CrocoBlock Support. But I dont have a staging environment on all my sites. I almost only run e-commerce websites, which I cant let run bug-free for a long time, as I often have a high number of visitors

Even if the problem is reproduced 1:1 on a test environment and an Illustrated guide or a screencast is sent, the Crocoblock Support almost needs administrative access.

Dont misunderstand me, your support is very good and always helps, but it is sometimes difficult for me to share my website if I dont have a staging environment.

In addition the last updates of JetSmartFilters and JetEngine had some bugs that also led to the critical error, which made the whole thing even more difficult.
I think its also a bit difficult for you because at this stage there arent that many use cases yet, as most people use Elementor.

But yes, if there are any serious bugs, I will go through support. Thank You!

**Comment by MjHead** [comment] 2024-02-15 15:55
@cwinkler8 We already looking into this issue, so no need to create a new ticket. I mean for the future - such cases faster to resolve with Support ticket. As ticket is most probably will be fixed with next update. It's about bugs, as for the feature requests - they processed with the same priority - from public git and from internal tickets

**Comment by MjHead** [comment] 2024-02-15 16:03
@hb81010 Yes, last time we have a bit hard times with some unexpected bugs after updates. Unfortunately such periods happens from time to time, when couple big updates of couple plugins overlaps in time. + Now rising up number issues related to Bricks, because more people start using in and now we faced much more different advanced use cases. It's a temporary situation, I think in next few releases we'll resolve most of problems. Sorry for the inconvenience

**Comment by cwinkler8** [comment] 2024-02-26 22:51
@MjHead thanks for fixing this in the 3.4.0-beta2 release. I can confirm that it's working again on my site. Much appreciated!

**Comment by Crocoblock** [comment] 2024-02-29 14:55
was released in 3.4.0

**Closed as completed by Crocoblock** 2024-02-29 14:55 UTC
Labels: bug, JetEngine
