### ISSUE TITLE
JetEngine <=3.2.4 + ACF 6.2.0 - Admin columns not retrieving svg image

### ISSUE THREAD

**Issue by mateitudor** [CrocoBlock/suggestions#7060] opened 2023-09-01 13:20 UTC
**Describe the bug**
When using Advanced Custom Fields for an icon, Jet Engine does not display it in the Admin Columns.

**To Reproduce**
1. Create an image meta field using ACF
2. Upload a svg image to a post / page
3. Create an Admin Column using JetEngine that uses the default custom fallback: jet_engine_custom_cb_render_image::product_icon_color::100
4. Go to the post list
5. Nothing gets displayed

**Expected behavior**
An image should display in the admin post list

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: agnostic

**Comment by mateitudor** [comment] 2023-09-01 13:30
Small update: tried using just JetEngine meta fields, without ACF, and I get the same result.

**Comment by kaskad88** [comment] 2023-09-07 13:27
Hello @mateitudor 

I tried to reproduce your steps and looks like all works fine https://tppr.me/NUAXZ

Please contact our support https://crocoblock.com/help-center/ for guidance in resolving this issue (and mention that you were directed by me and reference this issue.)

Thanks.

**Closed as completed by kaskad88** 2023-09-07 13:27 UTC
Labels: bug
