### ISSUE TITLE
JetEngine: Forms - WYSIWYG editor is marked as required even though there is no required option on setup.

### ISSUE THREAD

**Issue by dynamicwebdev** [CrocoBlock/suggestions#1897] opened 2020-09-19 19:13 UTC
WYSIWYG editor field is marked as required even though there is no required option on setup. Need to remove the required asterisk and need.

**Comment by MjHead** [comment] 2020-09-24 09:55
Hi! Can't reproduce this bug:
![image](https://user-images.githubusercontent.com/4987981/94130305-27bbea00-fe65-11ea-8e20-ea676c8daa53.png)
Could you plese share a website with the problem and screen of WYSIWYG set up

**Comment by kaskad88** [comment] 2020-10-16 13:06
Fixed in JetEngine 2.5.2

**Closed as completed by kaskad88** 2020-10-16 13:06 UTC
Labels: bug, JetEngine, need feedback
