### ISSUE TITLE
Jet Popup Disable Scrolling of background content

### ISSUE THREAD

**Issue by lukepatrickillustrations** [Crocoblock/suggestions#1459] opened 2020-06-17 13:29 UTC
Elementor Pro (built in) popups allow for you to disable scrolling when the popup is open. This is extremely critical when using Jet popups as single archive listings. A lot of times the content within the popup extends beyond the fold which would require the users to scroll (within the popup) to see the remaining content. But when the popup is open the user can still scroll both the popup content and the page behind the popup as well. This poses a user experience issue. 

As mentioned this feature/option is already built into elementor's popups but it would be fantastic if jet popup had those features as well. It's pretty much an absolute must have!

Thanks

<img width="297" alt="Screen Shot 2020-06-17 at 8 50 37 AM" src="https://user-images.githubusercontent.com/26655808/84903710-6ed35b80-b07c-11ea-8643-a43f13c11f7c.png">

**Comment by lukepatrickillustrations** [comment] 2020-06-17 13:30
The attachment has numerous options but the most critical is page scrolling.

**Comment by altechzilla** [comment] 2020-06-22 11:09
Duplicate of #1227

**Comment by shinTM** [comment] 2020-11-25 16:26
done v1.5.0

**Closed by shinTM** 2020-11-25 16:26 UTC
Labels: JetPopup, Pending

**Comment by Anpuu** [comment] 2024-03-18 14:51
it's not working.
