### ISSUE TITLE
[JetSmartFilters] When will you fix this bug? It's important 🐛

### ISSUE THREAD

**Issue by Medienor** [CrocoBlock/suggestions#3509] opened 2021-06-18 08:46 UTC
Hey, couple of weeks ago i updated to latest version of JetSmartFilters (Because i thought you release input field for slider)
But now there is a bug with the sliders, and sliders background color.

Can you please help us fix this?

https://prnt.sc/15sbm2w

**Comment by 79ho3ein** [comment] 2021-06-18 09:00
This problem does not exist and can be solved. Go to the elementor editor, (the same part where you used this widget)
Save changes again The problem is solved.
Unfortunately, jet smart filters add many bugs to each update. I wrote some of them in # 3486. I hope the developers solve these problems.
The bug you wrote about was fixed in a previous update and is now working properly.Good luck.

**Comment by Medienor** [comment] 2021-06-18 09:21
Hey @79ho3ein thanks for following me up brother.

What do you mean "Save changes again" ?

**Comment by 79ho3ein** [comment] 2021-06-18 09:28
hi @Medienor 
yes

**Comment by Medienor** [comment] 2021-06-18 09:36
> hi @Medienor
> yes

Does input values exsist for range slider? Where you can type in values instead of sliding slider?

**Comment by Floydtm** [comment] 2021-06-21 12:42
We tested it and it seems to be working correctly. However, our sites can be customized in different ways. Please contact our support team to resolve this request.

**Closed as completed by Floydtm** 2021-06-21 12:42 UTC
