### ISSUE TITLE
Parent Item ID is not set 

### ISSUE THREAD

**Issue by Radzio1615** [CrocoBlock/suggestions#5541] opened 2022-06-21 09:23 UTC
Hi! If user doesn't select connected related item, error message appear: 
"Parent Item ID is not set. Please check your form settings"

I'm using the checkbox field in the form to generate post list.

I don't require selecting the parent item.

How to ignore connection if user doesn't pick any?

After editing the post via form user should be redirected to the post. If user doesn't pick connection redirection doesn't work and error message appear.

**Comment by Floydtm** [comment] 2022-06-21 11:33
Describe your request in more detail, if possible, add screenshots or video. Thank you!

**Comment by Radzio1615** [comment] 2022-06-21 12:26
I created edit video form with Checkboxes field:

![image](https://user-images.githubusercontent.com/40895581/174794360-3b570008-5a4e-466d-8d6e-58760f104631.png)

Form has an action: Connect Relation Items 
![image](https://user-images.githubusercontent.com/40895581/174796135-d43f017c-7151-4a81-b006-6d7a8ee22524.png)

Also form has an action: Redirect to Page
![image](https://user-images.githubusercontent.com/40895581/174796583-329435db-6c99-4a99-b652-d6fab72fb20c.png)

User can add/edit video and select the playlist as he wishes or leave checkboxes unchecked.
![image](https://user-images.githubusercontent.com/40895581/174797562-b5a2a215-c4d3-43c3-8613-be2b1c6ab71d.png)

If playlist is selected, redirection is working fine.
If playlist is not selected, an error message appears below the form and redirection doesn't work.
![image](https://user-images.githubusercontent.com/40895581/174798074-cbf0c458-7c37-4b2b-8255-f24811a08ed0.png)

So how to remove error and how to make the redirect work if the playlist is not selected?

**Comment by MjHead** [comment] 2022-06-21 13:16
@Radzio1615 
Yes, for your case this error should not thrown. We'll fix this with 3.0,1 update, because 3.0.0 at the moment on the final stage of testing

**Comment by Radzio1615** [comment] 2022-06-21 13:17
@MjHead Thank you! There is one more thing I noticed. After selecting the playlist and saving the changes, the user cannot uncheck the playlist when re-editing the video.

**Comment by MjHead** [comment] 2022-06-21 13:20
> @MjHead Thank you! There is one more thing I noticed. After selecting the playlist and saving the changes, the user cannot uncheck the playlist when re-editing the video.

Ok, thanks for reporting. I'll reproduce your case and check both issues

**Comment by MjHead** [comment] 2022-07-08 07:49
Fixed. Will be released with 3.0.1 update

**Closed as completed by MjHead** 2022-07-08 07:49 UTC
Labels: bug, JetEngine, Done
