### ISSUE TITLE
Image ALT metadata not displaying properly on dynamic repeaters in Elementor

### ISSUE THREAD

**Issue by NoirMolk** [CrocoBlock/suggestions#5946] opened 2022-09-21 04:30 UTC
I created an Elementor template for pages with custom fields and repeaters for image text sections. Once the information is filled on the template, the front end displays ALT text from images within the repeater as the page title instead of the ALT text assigned to each image in the media folder. this happens with Dynamic image or an elementor image module using https://github.com/rtpHarry/jet-engine-repeater-values to select the repeater value, it doesn´t matter which one is used, the result is the image ALT displaying the wordpress page title as you can see here:

```

        <div class="jet-listing jet-listing-dynamic-image">
            <img src="DOMAIN NAME/Placeholder03.jpg" alt="CONTENT HERE IS EMPTY">
        </div>
```

Also as you can see here:
https://crocoblock.com/knowledge-base/articles/jetengine-dynamic-image-widget-overview/

The Custom Image Alt option is not even documented, so we can´t find a way to properly show the current image ALT meta data.

**Comment by kaskad88** [comment] 2023-06-02 06:36
Hello. I tried to reproduce your steps and looks like all works fine with JetEngine v3.1.5

If the issue still persists, please contact our support https://crocoblock.com/help-center/ for guidance in resolving this issue (and mention that you were directed by me and reference this issue.)

Thanks.

**Closed as completed by kaskad88** 2023-06-02 06:36 UTC
