### ISSUE TITLE
JetEngine: Make it possible to set publication date

### ISSUE THREAD

**Issue by HelmutGoebel** [CrocoBlock/suggestions#7221] opened 2023-12-04 16:24 UTC
The publication date of a post or a custom poste type can be manipulated, so the appearance of a particular post/cpt can be controlled. Unfortunatly this is not possible with cct. In certain cases, this is a big disadvantage, because I would need to use cpt instead of cct.

**Comment by Crocoblock** [comment] 2024-03-26 11:57
Done.

released in JetEngine v3.4.2

**Closed as completed by Crocoblock** 2024-03-26 11:57 UTC

**Comment by HelmutGoebel** [comment] 2024-03-26 12:39
Where?

[image: image.png]

Am Di., 26. März 2024 um 12:57 Uhr schrieb Crocoblock <
***@***.***>:

**Comment by HelmutGoebel** [comment] 2024-03-26 12:40
Sorry, saw it.

Am Di., 26. März 2024 um 13:39 Uhr schrieb Helmut Göbel <
***@***.***>:

**Comment by HelmutGoebel** [comment] 2024-03-27 17:19
Hi there,

that feature has a bug: When I try to save the post, it sets the
publication date and time to zero.

Best regards, Helmut


Am Di., 26. März 2024 um 13:40 Uhr schrieb Helmut Göbel <
***@***.***>:

**Comment by kaskad88** [comment] 2024-03-28 07:34
@HelmutGoebel 
Could you please attach a screen or a video because I tried to reproduce your issue and looks like all works fine

**Comment by HelmutGoebel** [comment] 2024-03-28 10:06
Hi Dmytro,

thanks for looking into it.

It is a bit more complicated, than I thought.

On the overview of CCT-items I display "Created Date" and "Modified Date".
The "Created Date" is correct, whe assuming, it is the "Published Date".
But when you look in the single view, the Date on "Item published" is empty.

[image: image.png]
List of cct-items

[image: image.png]
Single cct-item

Do you need any more information?

Best regards, Helmut

Am Do., 28. März 2024 um 08:34 Uhr schrieb Dmytro Bartoshchak <
***@***.***>:

**Comment by kaskad88** [comment] 2024-03-29 07:35
Hi @HelmutGoebel 
I can't see your screenshots https://prnt.sc/nZ5FJAEJAJ_K. 
Can you please attach screenshots again ?

**Comment by HelmutGoebel** [comment] 2024-03-29 09:11
Am Fr., 29. März 2024 um 08:36 Uhr schrieb Dmytro Bartoshchak <
***@***.***>:
