### ISSUE TITLE
Pagination problem when using products grid on category archive page

### ISSUE THREAD

**Issue by LevelUpGit** [CrocoBlock/suggestions#1877] opened 2020-09-17 10:06 UTC
We are experiencing issues with pagination on category(default woo categories) archive page(created with elementor).
When using jetwoobuilder - products grid with "Use Current Query" option enabled, pagination just disappears.
Thanks

**Comment by hossein7r** [comment] 2020-09-27 23:17
Yes I'm facing this exact same issue.
with "Current Query" enabled, only a handful of product will be shown which is specified in the "product numbers" field.
And pagination is just gone!

**Comment by redpanama** [comment] 2020-10-09 08:38
I can also confirm this, this is a critical bug it should be fixed asap. Thanks.

**Comment by Floydtm** [comment] 2020-10-09 12:20
For pagination to work correctly, you need to disable unnecessary providers in the filter settings https://prnt.sc/uw4h3j If you have any problems with this, please contact our support team. Thanks!

**Closed as completed by Floydtm** 2020-10-09 12:20 UTC

**Comment by LevelUpGit** [comment] 2020-10-09 16:36
@Floydtm  I can confirm, this working solution.
Thanks

**Comment by iamdanbarrett** [comment] 2020-11-28 18:15
@Floydtm The issue is, in the latest updates of your plugins it has broken the settings screen for the jetsmart filters and you cant access this anymore

**Comment by Floydtm** [comment] 2020-12-04 08:54
@iamdanbarrett We have fixed this bug. Update the plugin. Thanks you!
