### ISSUE TITLE
No way to Display CCT Repeater fields

### ISSUE THREAD

**Issue by IFTTD** [CrocoBlock/suggestions#3752] opened 2021-07-29 13:24 UTC
Currently I have not found a way to use repeater fields in Custom Content Types. One can add the repeater fields as usual but when it comes to displaying them. There is no functionality to do so both in the Dynamic Repeater Widget or in creating a Listing where only Post is an option.

**To Reproduce**
1. In Dynamic Widget Can not select a CCT
2. When creating a Listing a choosing Repeater field there is only Post Type. Custom Content Types do not show in List.
![image](https://user-images.githubusercontent.com/9660664/127499625-41337a24-c8db-4e35-9f97-d1774dc60080.png)

How was this missed?

**Comment by jamsheehan** [comment] 2021-07-29 19:49
Dupe of #2991

**Comment by drewbclark** [comment] 2022-04-09 09:22
I also have same issue! I find the repeater field to be useless without this. Please please add CCT Repeater Field Listing Support!

**Comment by kaskad88** [comment] 2022-04-29 09:36
Added in JetEngine v2.11.8

**Closed as completed by kaskad88** 2022-04-29 09:36 UTC
