### ISSUE TITLE
Elementor 3.0.3 BUG with Jet-engine activated

### ISSUE THREAD

**Issue by quentinaurat** [CrocoBlock/suggestions#1790] opened 2020-08-27 20:07 UTC
**Describe the bug**
"TypeError: Cannot set property children of #<Container> which has only a getter at [...]"
Seems to be related to the "Repeater" type of thing. I'was expecting this one to be fixed by both Elementor and Crocoblock Team, the new release of Elementor throw the error again with jetEngine activated only... It result an unserviceable site, so it's pretty high priority, I gess.

**To Reproduce**
1. install a bare bone WP (hello theme in my case)
2. install Elementor 3.0.3 free with WP extension manager
4. Create a page and edit it via Elementor, create a section with title and a text block for instance. Then publish.
3. install Jet-engine with your Licence as usual.
5. Edit the page, now you do something like moving, removing, duplicate any element, console should throw the error Elementor editor start do mess with template.

**Expected behavior**
( step 5 describe the bug properly )
note you can simply create a page with jet engine installed, the error result the same.

**Desktop (please complete the following information):**
 - OS: mac osx 10.14.6
 - Browser Chrome (84.0.4147.125)
 - WP Version 5.5

**Comment by neosaveme-zz** [comment] 2020-08-27 21:52
after the **elementor 3.0** update the whole ecosystem of plugins around elementor with **no exceptions** has bugs and feedback is all over the net right now. the developers did not have enough time to adapt even after a fix . 
I figured out that **the Dynamic Visibility for Widgets and Sections module** was the cause of the problems in jetengine right now at the moment so it **must be deactivated**.  while waiting for them to make all the tests and debug to adapt their solutions to the new elementor 3.0 update

**Comment by quentinaurat** [comment] 2020-08-27 22:41
@neosaveme, Thanks for pointing me "the Dynamic Visibility for Widgets and Sections module" as a cause of the issue. I'm still not lucky because I use it A LOT... I'll wait a new release.

**Comment by kaskad88** [comment] 2020-08-28 07:44
Fixed in JetEngine v2.4.11. Feel free to update!

**Closed as completed by kaskad88** 2020-08-28 07:44 UTC
