### ISSUE TITLE
Ability to disable mouse scrolling in the product grid widget (desktop)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4459] opened 2021-12-03 13:00 UTC
hello
Now, users can navigate the carousel of products using the mouse. Of course on the desktop. But it does not make good sense to users. Because they use the next and previous buttons to scroll.Not from the mouse.
If possible, please add an option so that we can disable the ability to scroll with the mouse. We only enable this option on desktop carousels. Not mobile and tablet.

https://user-images.githubusercontent.com/77163248/144606502-b027ad9b-0445-4773-946c-80e6dde33a62.mp4

In fact, on the desktop, we use the before and after buttons to flip through product carousels. Therefore, there is no need to flip through the products using the mouse in desktop. 

thank you

**Comment by Michaelgimii** [comment] 2021-12-15 09:32
+1
In the new version, there is a problem that will be fixed by adding this feature. The problem is that sometimes, on the desktop, if we click on a product, the carousel scrolls. Without hitting the left and right buttons to scroll.
hi @UraraReika , Please add this option to the new version. It's excellent.

**Closed as completed** 2022-02-16 07:47 UTC
Labels: JetWooBuilder, Done
