### ISSUE TITLE
JetMenu added custom fonts through the Elementor causing the errors in concole

### ISSUE THREAD

**Issue by dislokacia** [CrocoBlock/suggestions#1996] opened 2020-10-12 07:00 UTC
JetMenu added custom fonts through the Elementor causing the errors in concole. The added font is automatically searched in googlefonts list, but the menu can't find it there.
The font is displayed properly. The problems are the console errors

**Comment by bowmandesign** [comment] 2020-10-26 16:20
Hi Crocoblock,

First, thank you for all that you do. You have created a great framework!

I originally reported this issue 20 days ago and was wondering if I could help in anyway to close the issue?

When debugging why JetMenu is looking for custom non-google fonts from within the Google Font list, there are 2 use cases to consider.

1. JetMenu is requesting Custom fonts stored on the server (/wp-content/fonts/) setup via the Elementor Pro Custom Fonts settings from within the Google Font List, despite the fact that they are not Google fonts.
2. JetMenu is requesting Adobe fonts, fonts.adobe.com, from within the Google Font List, despite the fact that they are not Google fonts.

The reason fonts are displaying correctly, despite the incorrect JetMenu Google Font request for Custom Fonts, is that Elementor Pro is pushing them through as the Hello theme and Elementor site settings are setup correctly.

We are hoping to push this through with a fix soon, customers are noticing the console errors.

Best Regards,
Bill

**Comment by shinTM** [comment] 2020-10-29 08:36
done v2.0.7

**Closed as completed by shinTM** 2020-10-29 08:36 UTC
Labels: JetMenu, Pending

**Comment by bowmandesign** [comment] 2020-11-05 15:25
Thank you very much, with the 2.0.7 release yesterday, I installed the update and the problem is gone.

Best regards,
